app:

  factories:
    user: ${class:uvcreha.models.User}

  session:
    cache: ${path:var/sessions}
    cookie_name: docmanager.cookie
    cookie_secret: secret

  env:
    session: docmanager.session
    user: docmanager.user

  logger:
    name: docmanager.logger

  assets:
    compile: True
    recompute_hashes: True
    bottom: True
    publisher_signature: static

  storage:
    root: ${path:storage}
    schemas: ${path:schemas}


arango:
  user: root
  password:
  database: docmanager
  url: http://127.0.0.1:8529


amqp:
  url: amqp://guest:guest@localhost:5672//
  serializer: json


environ:
  CHAMELEON_CACHE: var/templates_cache
  CHAMELEON_RELOAD: "1" 


server:
  host: 0.0.0.0
  port: 8080


defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog


webpush:
  public_key: ${path:identities/public_key.pem}
  private_key: ${path:identities/private_key.pem}
  vapid_claims:
    sub: mailto:cklinger@novareto.de
    aud: https://updates.push.services.mozilla.com


emailer:
  host: localhost
  user:
  password:
  port: 25
  emitter: docmanager@novareto.de
