components: !include:components.yaml

logger: !apply:logging.basicConfig
   level: !name:logging.INFO


loaders:
  - !name:horsebox.utils.modules_loader
    - !module:uvcreha
  - !name:uvcreha.jsonschema.store.load_from_folder
    - !new:pathlib.Path [schemas]


# amqp: !new:reiter.amqp.mq.AMQPCenter
#   - user_new: !new:kombu.Queue
#       name: creation
#       routing_key: user.new
#       exchange: !ref <mq_exhange>
#     user_edit: !new:kombu.Queue
#       name: edition
#       routing_key: user.edit
#       exchange: !ref <mq_exhange>
#   - !name:uvcreha.amqp.UserCreationConsumer


# workers:
#    amqp: !new:reiter.amqp.worker.Worker
#      amqpcenter: !ref <amqp>
#      url: amqp://guest:guest@localhost:5672//
#      app: !ref <components[uvcreha]>


environ:
  CHAMELEON_CACHE: var/templates_cache
  CHAMELEON_RELOAD: '1'


browser: !apply:horsebox.utils.apply_middlewares
  canonic: !ref <components[uvcreha]>
  middlewares:
    - !ref <components[assets]>
    - !ref <components[session]>
    - !ref <components[authentication]>

runner: !name:bjoern.run
  host: 0.0.0.0
  port: 8080
  reuse_port: true
  wsgi_app: !ref <browser>
