components: !include:components.yaml

schemas: !apply:uvcreha.jsonschema.store.load_from_folder
  - !new:pathlib.Path [schemas]

logger: !apply:logging.basicConfig
   level: !name:logging.INFO    

modules:
  - !module:uvcreha
  - !module:bg.example

workers:
   amqp: !new:reiter.amqp.worker.Worker
     amqpcenter: !name:reiter.amqp.mq.AMQP
     url: amqp://guest:guest@localhost:5672//
     app: !ref <components[uvcreha]>

environ:
  CHAMELEON_CACHE: var/templates_cache
  CHAMELEON_RELOAD: '1'


browser: !apply:horsebox.utils.apply_middlewares
  canonic: !ref <components[uvcreha]>
  middlewares:
    - !ref <components[assets]>
    - !ref <components[session]>
    - !ref <components[authentication]>

runner: !name:bjoern.run
  host: 0.0.0.0
  port: 8080
  reuse_port: true
  wsgi_app: !ref <browser>
